XENONnT/utilix

- utilix/config.py
- utilix/rundb.py
- I started to add some helpful http error messages for failing requests
- Init & run number / run name selection is separated from each other
- Interlock run name and run number (both are valid parameters after a cross check with the runDB
- Focus on the data field: added a replace_data function to allow user to exchange a certain dictionary in the data 'list' by a new one
> Minor improvements in handling

- utilix/config.py
config_file_path is not defined and will cause crashes that are not making much sense later.
> fix unboundlocalerror

- utilix/rundb.py
Joran had the nice suggestion to perform a test of the mongo client in utilix so that we can give better error messages if needed. This is a slight modification of that to test the actual collection instead of the client, since I was having issues with the client checks. 
The main issue this is trying to solve is not really a utilix problem. For XENON, we need to pass `readPreference='secondaryPreferred'` to the pymongo client for things to work properly with our mirrors (or only pass a single accessible mirror, ie not LNGS). This flag gets passed automatically when using the `pymongo_collection` function of utilix; however, if someone is using the utilix config to setup a MongoClient without using this `pymongo_collection` function there could be problems if they don't pass the right …
> Check collection instead of client

- tests/test_url.py
- utilix/rundb.py
We have recently seen that this can cause errors:
https://xenonnt.slack.com/archives/C016DM0JPK9/p1605866361323700
This can be avoided by the read-preference, therefore we may just raise a warning rather than an Error (what I did first). Let me know if you think this is still necessary.
> Warn when not being able to get server_info

- .github/workflows/Pipi.yml
Use github actions to install utilix. Fix issue https://github.com/XENONnT/utilix/issues/12
Straxens docs were failing due to utilix not being pip installable. That is a thing of the past with this PR. Will have to check that my secrets of my fork are also on the XenonnT repo.
**Result**
```pip install utilix```. Tada
> Use github actions to pip install utilix

- utilix/batchq.py
- utilix/rundb.py
This includes (1) a bug fix in the Token class where the authentication got messed up and (2) a new module called batchq that can be used for easy job submission to the midway queue. As an example, in a python script you could do:
```
from utilix.batchq import submit_job
job_script = 'python -c import straxen; print(straxen.__version__, straxen.__file__)'
submit_job(job_script)
```
While you don't need to pass them, usually you would want to include more kwargs, e.g.:
```
submit_job(job_script, log='path/to/log', jobname='your_jobname', mem_per_cpu=4000)
```
By default the job will run inside the development base env container, but you can specify to not use container or use a different one with another kwarg.
> Bug fix in token and add utilix.batchq 

- utilix/config.py
- utilix/rundb.py
This PR includes
1. Adds a `logging_level` attribute to the utilix Config class, so that you can set the logging level in your config. I already updated the global config level on midway. It defaults to 'WARNING' if no option is passed. 
2. Cleaned up the Token class more, hopefully resolving all the bugs we're seeing with authentication. It's a bit difficult to test every scenario, but it resolves @SidAhmedMa's issue. 
3. Generally better error handling. Again I'm not sure I've satisfied everything, but hopefully the error messages will be more helpful now. For example, bad API calls raise a RuntimeError so that we don't get that useless `KeyError: 'results' not in the dict` error downstream.
> Logging level, token bug fixes, and error handling

- utilix/rundb.py
This one option is associated to failures on the event-builders. I'm quite puzzled as to why but for now it might be saver to disable such an option.
> Update rundb.py for smooth processing at DAQ

- .gitignore
- utilix/rundb.py
This PR implements two different functions for setting up the xenon1t and xenonnt collections respectively. It deprecates the old `pymongo_collection` function in favor of `xe1t_collection` and `xent_collection` functions. 
To use this functionality, you need to modify your xenon_config to have 
```
[RunDB]
xent_url = 
xent_user = 
xent_password =
xent_database = 
xe1t_url =
xe1t_user = 
xe1t_password = 
xe1t_database = 
```
This should make it easier to work with both xenon1t and xenonnt run databases simultaneously without modifying your config file.
> Different collections for 1T and nT

- .bumpversion.cfg
- .gitignore
- utilix/__init__.py
Add version to utilix such that people can do `print(utilix.__version__)`. Also update a bumpversion config such that these things can be done automatically:
```bash
bumpversion patch 
git push --tags
```
> add version to utilix package

- utilix/rundb.py
`nt_collection` and `1t_collection` should be `xent_collection` and `xe1t_collection`.
> Fix pymongo_collection warning typo

- utilix/__init__.py
- utilix/mongo_files.py
- utilix/rundb.py
Tweaks to #35.
In this PR:
- We added the mongo downloader/uploader etc from straxen.
- We subclass the mogno downloader&uploader to an API variant.
- Placeholders for the API calls are added (sorry these are hard to tests without setting up another API).
> Use gridfs on mongo and API

- utilix/__init__.py
- utilix/rundb.py
This addresses #34. It introduces a new config option in the utilix config that looks like this: 
```
[utilix]
initialize_db_on_import = true
```
If the field doesn't exist or `initialize_db_on_import=false`, then utilix will not initialize a DB class instance. 
Since I imagine users will most likely want this feature, a warning statement is printed if the DB class is not instantiated: 
```
(XENONnT_development) bash-4.2$ python -c "import utilix"
Warning: DB class NOT initialized on import. You cannot do `from utilix import db`
If you want to initialize automatically on import, add the following to your utilix config:
[utilix]
initialize_db_on_import=true
```
> Use config option for initializing DB class or not

- utilix/__init__.py
- utilix/batchq.py
- utilix/config.py
- utilix/rundb.py
Slight tweak to recent PRs, without utilix config file, it would still be nice if `import utilix` doesn't fail. 
**Can you give an example**
```bash
python -c "import utilix"
```
See:
https://github.com/XENONnT/straxen/pull/436/checks?check_run_id=2327495931
Perhaps we should write a test for these sorts of things.
> allow import without file

- utilix/io.py
- utilix/rundb.py
This includes a few improvements with the runDB operations
- Raise an error if API calls failed to catch them better
- Add a filter kwarg to DB.get_data to allow users to select the data entries they are most interested in, rather than including a list of ~50 data entries (or more even)
- Adds a cleanup_datadict function that is used to prune off data fields before sending to the runDB API, which has a strict policy of what fields it knows about. 
- Small updates in io.py
> Few improvements

- utilix/rundb.py
This caches the Mongo client so that we don't create multiple such objects, as warned against [here](https://pymongo.readthedocs.io/en/stable/faq.html). It also allows for (but doesn't require) 3 more config options in the xenon_config: 
```
[RunDB]
...
max_pool_size=<maxPoolSize>
socket_timeout=<socketTimeoutMS>
connect_timeout=<connectTimeoutMS>
```
These have default values hardcoded.
> Cache mongo client

- utilix/batchq.py
Allow scripts to be saved in case the user wants to. Also remove the `delete_file` argument as /tmp/  files are removed so quickly that it doesn't really make sense to pretend that these files stick arround.
> allow the saving of scripts

- utilix/batchq.py
Use `--time` in the `.sbatch` script to limit the time a job use. 
The default max job time is set to be 24hr which is suitable for most jobs. 
Additionally, solve a bug when removing the temporary `.sbatch` file.
> Set max wall time of a job

- utilix/batchq.py
When submitting jobs to midway's batch queue, some env variables get passed to the job. This includes CUTAX_LOCATION, which is what is used to pass a particular cutax version/path. This leads  to unexpected results if, e.g., someone submits a job specifying a container (say `2022.02.4`) from inside a different cvmfs env (say `development`). This PR should fix that issue.
> Add CUTAX_LOCATION to unset list

- utilix/processing_requests.py
Just realised that Evans comment about using uconfig is also relevant to some other values i read from env variables or hardcoded.
Now use uconfig for:
- api url
- api token/username and password
- API audience
Also adding some helpers that will be useful for automating job submission
> Use uconfig for api config management

- utilix/batchq.py
This PR adds the keyword `node` into the submission function.
With which the user is able to select onto which node their job should be submitted to.
Also the keyword `exclusion_list` ist added, which allows to define a list of nodes that should not be used for submission.
> Added keyword function to specify which node a job should run on

- utilix/batchq.py
With this PR I would like to introduce the possibility to have dependencies on jobs using the batchq.submit_job function.
Now the function returns the job_id if the job submission succeeded, so that a user can use a script to submit jobs, get the ids of the submitted jobs, and submit a secondary job that will start only when the initial jobs will complete with exit code 0. 
Example script to use the new functionality: 
```
submitted_jobs = []
for i in range(5):
job_id = batchq.submit_job(jobstring, 
jobname=jobname, 
partition='dali', 
)
submitted_jobs.append(job_id)
if not None in submitted_jobs:
job_id = batchq.submit_job(jobstring, 
jobname='afterok', 
partition='dali',
dependency=submitted_jobs)
```
.
.
.
See slurm sbatch [documentation](https://slurm.schedmd.com/sbatch.html):
-d, …
> Return job id and allow for dependencies

- utilix/batchq.py
Currently we use `os.getlogin()` to get user name, but this is gonna crash if you are in midway3 notebooks. However, same functionality can be replaced by `os.environ["USER"]`, as @jingqiangye suggested.
> Use environment variable to know user name

- README.md
- requirements.txt
- setup.py
- utilix/__init__.py
- utilix/batchq.py
I refactored batchq.py to implement #85
Changes include:
- Using [simple_slurm](https://github.com/amq92/simple_slurm) for more generic and robust sbatch script generation.
- Using [pydantic](https://github.com/pydantic/pydantic) for data validation. This validates user inputs before any job submission and provides us with better error messages to reduce human errors.
- Updating version number to `0.8.0`.
- Updating documentation.
> Completely refactor batchq using simple_slurm and pydantic

- .gitignore
- utilix/batchq.py
Changes:
1. Follow Python PEP8 Style Guide to improve code style
2. Follow Python PEP484 to type hint variables and interface boundaries (args and returns)
3. Avoid using f-string or lazy `%` formatting for log messages to prevent unpredictable behaviors.
4. Update docstring
> Improve code readibility

- tests/test_batchq.py
- utilix/batchq.py
- Add clear error type like `QOSNotFoundError`. So that users could do the following to bypass some of the validators:
```
try:
job_submission=JobSubmission()
except QOSNotFoundError:
pass
```
- Add a unittest for batchq
> Clear error type

- utilix/batchq.py
Before this PR, when submitting any job, an error shows:
```
pydantic.error_wrappers.ValidationError: 1 validation error for JobSubmission
bypass_validation
none is not an allowed value (type=type_error.none.not_allowed)
```
because we assigned default `bypass_validation` as `None`:
https://github.com/XENONnT/utilix/blob/6c39370a8f5c972571b0366bdee78abcec69da9e/utilix/batchq.py#L498
> Set default `bypass_validation` as empty list

- utilix/batchq.py
[slack thread](https://xenonnt.slack.com/archives/C016DM0JPK9/p1713050982417609)
Because when requiring memory larger than 32GB, somehow the `xenon1t` partition will not submit the job if you specify `exclude_lc_nodes` as True.
We should consider `_get_lc_nodes` as an experimental feature.
> Set default `exclude_lc_nodes` as False

- tests/test_batchq.py
- utilix/batchq.py
Pydantic validators are called according to the sequence of the input arguments. In the old code "bind" was behind "partition", so the binding reset for dali https://github.com/XENONnT/utilix/blob/4bf968290ecaa96f8ae6c9cf16f6c9f75add3813/utilix/batchq.py#L211
doesn't actually work, as the bind will be overwritten in the bind validator.
This PR fixes this problem by moving "bind" in front of "partition"
> Fix dali binding

- tests/test_batchq.py
- utilix/batchq.py
As discussed in [this slack thread](https://xenonnt.slack.com/archives/C017J7ELYU8/p1716524566325289), the instability of mounting affects the performance of `env_starter` and `batchq`. 
To avoid manually modifying the codes based on the variant status of servers, a better practice is to put all possible bindings and image locations in those two modules and do an automatic check to avoid problematic ones. By doing that, we can guarantee that users will get all of the possible resources without touching the inner side of the tools. The implementation of image location checking was done in #108, and here, we also added a similar function to the binding. 
The unit tests are also updated accordingly. I have run the tests on midway2, midway3 and dali and on all servers they are working well.
> Auto check binding

- tests/test_batchq.py
- utilix/batchq.py
- utilix/rundb.py
In the current `rundb.py` the read preference for the MongoDB client is set to be `SecondaryPreffered`. But it doesn't stop the client from reading from the primary when the secondaries are not available. As the network bandwidth of the primary one is not satisfactory, we should avoid reading from the primary and just read from the secondaries.
Reference: the documentation of `pymongo` about the read preference:
https://pymongo.readthedocs.io/en/stable/api/pymongo/read_preferences.html
> Change read preference

- utilix/__init__.py
- utilix/config.py
- utilix/rundb.py
For example after this PR you can control the logging of other packages like:
```
set_logging_level("urllib3", "WARNING")
```
to make `request` package to be quiet, as suggested by https://stackoverflow.com/a/11029841/16515081.
> Add more function to manipulate logging

- utilix/__init__.py
- utilix/shell.py
- utilix/x509.py
Move `Shell` from outsource https://github.com/XENONnT/outsource/blob/8371899473b90aeb07178163fd34e81cafc66eb1/outsource/shell.py#L8 to utilix, because it is used also in other OSG base submitters: https://github.com/XENONnT/alea/blob/087ff3bb8e56994279a5e577e85260e9c256285b/alea/submitters/htcondor.py#L742.
The same motivation applies to `_validate_x509_proxy`.
> Add a shell script module

- utilix/tarball.py
1. `Tarball.is_user_installed` test whether a package is user installed
2. `Tarball.get_installed_git_repo` returns the repo where the editable user-installed package is from
3. `Tarball.create_tarball` create a tarball of the git repo, while ignoring the git-ignored files
After `Tarball.create_tarball`, you can `mkdir strax && tar -xzf strax.tar.gz -C strax --strip-components=1` to extract the package into `strax` folder. Here `--strip-components=1` is to strip the first folder level. This is to be compatible with the file structure of [deployed](https://xenon1t.deployhq.com/projects/cutax/overview) cutax. You can find them at `/ospool/uc-shared/project/xenon/xenonnt/software/cutax`.
> Add a class to tarball the editable user-installed package from git repo

- utilix/rundb.py
By setting `rundb_retry = 0` in your `XENON_CONFIG`, format similarly to `rundb_api_url`, you can control the number of retries of making new tokens.
> Use `RunDB.rundb_retry` in `XENON_CONFIG` to control number of retry

- utilix/tarball.py
Without this PR, we will see:
```
Traceback (most recent call last):
File "/home/xudc/tt.py", line 4, in <module>
Tarball.get_installed_git_repo("rucio")
File "/home/xudc/utilix/utilix/tarball.py", line 78, in get_installed_git_repo
repo = Repo(mod.__path__[0], search_parent_directories=True)
File "/cvmfs/xenon.opensciencegrid.org/releases/nT/el9.2024.09.1/anaconda/envs/XENONnT_el9.2024.09.1/lib/python3.9/site-packages/git/repo/base.py", line 236, in __init__
raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /cvmfs/xenon.opensciencegrid.org/releases/nT/el9.2024.09.1/anaconda/envs/XENONnT_el9.2024.09.1/lib/python3.9/site-packages/rucio_clients-32.8.0-py3.9.egg/rucio
```
This is because rucio is not an ordinarily installed package.
> Exempt `OSError` for `Tarball.get_installed_git_repo`

- utilix/rundb.py
Close: https://github.com/XENONnT/outsource/issues/147
The current problem is:
1. 80 is not allowed to generate `.dbtoken`
2. 5000 is blocked by OSG so it can not be used for DB operation
After this PR, you can set `XENON_CONFIG` as:
```
[RunDB]
rundb_api_url = http://******:80
tk_rundb_api_url = http://******:5000
```
> Use another rundb url `tk_rundb_api_url` to generate token

- utilix/mongo_files.py
- utilix/rundb.py
If we are sure that nowhere in nT we are still using `utilix.rundb.pymongo_collection`.
> Remove `pymongo_collection` because it is deprecated

- pyproject.toml
- utilix/scripts/xefind.py
Alternative to https://github.com/XENONnT/straxen/pull/1434
> Add xefind script

- tests/test_batchq.py
- utilix/batchq.py
This error is raised when submitting jobs to DALI compute nodes. However, `SCRATCH_DIR` is only used in `TMP_DIR` a few lines later, which is hardcoded to be at `/dali/lgrandi/{USER}/tmp` for DALI jobs anyway.
> Fixed unnecessary error raising for DALI jobs

- utilix/mongo_storage.py
This means always redownloading files if using a readable filename.
Cache invalidation.
> Do not check cache if downloading readable filename

- utilix/__init__.py
- utilix/batchq.py
A straightforward fix for a stupid typo... The singularity alias should be a string but not a dict
> Fix typo in singularity alias

- utilix/install.sh
Sometimes there is not internet connection on computing nodes.
> Install with `--no-build-isolation` to avoid poetry installation

- utilix/tarball.py
If there is no `__init__.py` in the repo (like https://github.com/jelleaalbers/multihist), the `__path__` does not exist.
> Find repo without `__init__.py`

- utilix/batchq.py
When running jobs on OSG nodes, we can not know the servers' hostnames.
> Allow unknown server
