utilix/config.py, utilix/rundb.py
Have utilix raise a FileNotFoundError if no proper config is passed.
=> Raise error

utilix/rundb.py
I thought that https://github.com/XENONnT/utilix/pull/10 would be all we need but it seems I mist some places (https://xenonnt.slack.com/archives/C016UJZ090B/p1606818679355200).
=> Safe operations for dicts

utilix/config.py
=> Add windows compatibility

utilix/rundb.py
There is no return, make sure we don't run into errors with self.refresh()
=> Small fix, self.new_token does not return

utilix/rundb.py
In https://github.com/XENONnT/utilix/pull/22 I missed the rundb place of the usage of $home
=> add windows support for rundb

utilix/rundb.py
Fix confused statements on `#tech-support`
=> Increase JSONDecodeError readability

utilix/rundb.py
Adds a few MC methods for the rundb API
=> Add MC methods

utilix/__init__.py
Work on https://github.com/XENONnT/straxen/issues/350
=> Utilix import

utilix/__init__.py, utilix/batchq.py, utilix/config.py, utilix/rundb.py
@jorana sorry, I should've tested this. How about something like this instead? Then things can be initialized still without a bunch of Nones.
=> Allow import without config file but without a bunch of Nones

README.md
=> Update pipy badge

requirements.txt, utilix/io.py
Allow commentsjson as it is used for MC files
=> allow commentjson

.github/workflows/test_package.yml, requirements.txt, utilix/__init__.py
Copy one of the other CI github action tests to also run on utilix.
=> Ci test & specify requirements

utilix/__init__.py
=> None config for no file

utilix/mongo_files.py
=> Compute md5 before upload

README.md, requirements.txt, scripts/processing_server.py, utilix/__init__.py, utilix/processing_requests.py
This PR adds some utility functions for communicating with the processing requests API server as well as adding a method to the strax Context class and defining a basic API server in the scripts folder
Example usage:
```python
st = straxen.test_utils.nt_test_context()
requests = st.request_processing('012882', # can be a tuple of run_ids
'event_basics', # must be a single data type
priority=1, # higher values mean higher priority, defaults to -1
comments='this is for the new elife analysis', # add some comments to help people reviewing the requests.
submit=True, #If you use `submit=False` the requests objects will be created but no submitted.
)
```
Will add some tests and extra functionality soon
=> Processing requests

utilix/batchq.py
Fix https://xenonnt.slack.com/archives/C016DM0JPK9/p1649746872449369?
=> Prevent making same file descriptor

.bumpversion.cfg, setup.py, utilix/__init__.py
Forgot to bump version to v0.7.4 in that release...
=> bump version

.bumpversion.cfg, setup.py, utilix/__init__.py, utilix/batchq.py
Just to avoid this happening again:
```
PermissionError: [Errno 13] Permission denied: '/scratch/midway3/tmp'
```
=> Midway3 tmpdir

utilix/batchq.py
=> Support for caslake

utilix/batchq.py
=> Do NOT unset CUTAX_LOCATION when specified local cutax

utilix/batchq.py
Based on #82 , just give more debug information.
=> More printout in local cutax scenario

utilix/batchq.py
The loosely coupled (lc) nodes don't have access to `/project,` and therefore, there might be a data availability issue, as described in #87 . In the future, the users should only use the lc nodes when they are sure they don't need the access to `/project`. To avoid submitting to the lc nodes blindly, the default option is set as `True`
=> Add the exclude_lc_nodes option

.bumpversion.cfg, .gitignore, requirements.txt, utilix/batchq.py
- Updated the pydantic requirement
- Add a check for positional arguments
- Bump version to 0.8.2
=> Verified Compatibility with Pydantic v1

tests/test_batchq.py, utilix/batchq.py
=> Remove duplicated argument `bypass_validation`

utilix/batchq.py
=> Use bash shell to submit sbatch

tests/test_batchq.py, utilix/batchq.py
We only tested the initialization of the `JobSubmission` class previously.  It's also helpful to actually test the submission
=> Add unittest for the job submission

utilix/rundb.py
Adding more flexibility from config to make pymongo client
=> More mongodb options

utilix/batchq.py
=> Move binding before partition

utilix/io.py, utilix/x509.py
In that case, you should use `eval`.
=> Cover the case where the stdout is "-1"

tests/test_batchq.py, utilix/batchq.py
#151 
Same solution as in `env_starter`
=> Fix midway3 singularity

utilix/mongo_storage.py
=> Revert "md5_stored check also config name"
